language: python
python:
  - "3.8"
addons:
  ssh_known_hosts: 157.245.101.118
before_install:
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
install:
  - pip install -r requirements.txt
  - pipenv install
  # - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmwXogdW9VG9MwvKbP8vfRdrhusVH62jVkMSR7FdSNa1l4kYsaiDsCvrU2ptV16Zw+nUHsPxrqi0I8te2XWoVeYgizNZIn+0yZ2Bswbdu+iIz09fbPJRlfbB9hpstyh9Fw45Hiavpb6iverTGIppzssJlvISxHafRljID0o+rkRvK0fy08RhAtI7oVPj+xdp3yhTVjBJ2/i2m3iZ8iBa0BdeSw8WE6YdK4VPhQ2aeDsieTZnT9H5qCudrHmjCX2PAPL0vKR46hXn6DU/BoxmDdkNTiUlKeE4QANBo0Y+i3FPrpxI7qXIlFIsjRV4L/LNrJMc90zxYJegAvX36NwwUX abhi_ap@Abhi-Dell' >> $HOME/.ssh/known_hosts
script:
  - "true"
after_success:
  - bash ./deploy.sh
notifications:
  email:
    recipients:
      - abhi_ap@hotmail.com
    on_success: always
    on_failure: always
